/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiElevenlabsScribeTokenRouteImport } from './routes/api/elevenlabs/scribe-token'
import { Route as AuthenticatedSessionsNewRouteImport } from './routes/_authenticated/sessions/new'
import { Route as AuthenticatedSessionsSessionIdWrapRouteImport } from './routes/_authenticated/sessions/$sessionId/wrap'
import { Route as AuthenticatedSessionsSessionIdWorkspaceRouteImport } from './routes/_authenticated/sessions/$sessionId/workspace'
import { Route as AuthenticatedSessionsSessionIdLobbyRouteImport } from './routes/_authenticated/sessions/$sessionId/lobby'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiElevenlabsScribeTokenRoute =
  ApiElevenlabsScribeTokenRouteImport.update({
    id: '/api/elevenlabs/scribe-token',
    path: '/api/elevenlabs/scribe-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSessionsNewRoute =
  AuthenticatedSessionsNewRouteImport.update({
    id: '/sessions/new',
    path: '/sessions/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsSessionIdWrapRoute =
  AuthenticatedSessionsSessionIdWrapRouteImport.update({
    id: '/sessions/$sessionId/wrap',
    path: '/sessions/$sessionId/wrap',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsSessionIdWorkspaceRoute =
  AuthenticatedSessionsSessionIdWorkspaceRouteImport.update({
    id: '/sessions/$sessionId/workspace',
    path: '/sessions/$sessionId/workspace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsSessionIdLobbyRoute =
  AuthenticatedSessionsSessionIdLobbyRouteImport.update({
    id: '/sessions/$sessionId/lobby',
    path: '/sessions/$sessionId/lobby',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
  '/sessions/$sessionId/lobby': typeof AuthenticatedSessionsSessionIdLobbyRoute
  '/sessions/$sessionId/workspace': typeof AuthenticatedSessionsSessionIdWorkspaceRoute
  '/sessions/$sessionId/wrap': typeof AuthenticatedSessionsSessionIdWrapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
  '/sessions/$sessionId/lobby': typeof AuthenticatedSessionsSessionIdLobbyRoute
  '/sessions/$sessionId/workspace': typeof AuthenticatedSessionsSessionIdWorkspaceRoute
  '/sessions/$sessionId/wrap': typeof AuthenticatedSessionsSessionIdWrapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
  '/_authenticated/sessions/$sessionId/lobby': typeof AuthenticatedSessionsSessionIdLobbyRoute
  '/_authenticated/sessions/$sessionId/workspace': typeof AuthenticatedSessionsSessionIdWorkspaceRoute
  '/_authenticated/sessions/$sessionId/wrap': typeof AuthenticatedSessionsSessionIdWrapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/sessions/new'
    | '/api/elevenlabs/scribe-token'
    | '/sessions/$sessionId/lobby'
    | '/sessions/$sessionId/workspace'
    | '/sessions/$sessionId/wrap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/sessions/new'
    | '/api/elevenlabs/scribe-token'
    | '/sessions/$sessionId/lobby'
    | '/sessions/$sessionId/workspace'
    | '/sessions/$sessionId/wrap'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/sessions/new'
    | '/api/elevenlabs/scribe-token'
    | '/_authenticated/sessions/$sessionId/lobby'
    | '/_authenticated/sessions/$sessionId/workspace'
    | '/_authenticated/sessions/$sessionId/wrap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiElevenlabsScribeTokenRoute: typeof ApiElevenlabsScribeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/elevenlabs/scribe-token': {
      id: '/api/elevenlabs/scribe-token'
      path: '/api/elevenlabs/scribe-token'
      fullPath: '/api/elevenlabs/scribe-token'
      preLoaderRoute: typeof ApiElevenlabsScribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sessions/new': {
      id: '/_authenticated/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AuthenticatedSessionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$sessionId/wrap': {
      id: '/_authenticated/sessions/$sessionId/wrap'
      path: '/sessions/$sessionId/wrap'
      fullPath: '/sessions/$sessionId/wrap'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdWrapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$sessionId/workspace': {
      id: '/_authenticated/sessions/$sessionId/workspace'
      path: '/sessions/$sessionId/workspace'
      fullPath: '/sessions/$sessionId/workspace'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$sessionId/lobby': {
      id: '/_authenticated/sessions/$sessionId/lobby'
      path: '/sessions/$sessionId/lobby'
      fullPath: '/sessions/$sessionId/lobby'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdLobbyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSessionsNewRoute: typeof AuthenticatedSessionsNewRoute
  AuthenticatedSessionsSessionIdLobbyRoute: typeof AuthenticatedSessionsSessionIdLobbyRoute
  AuthenticatedSessionsSessionIdWorkspaceRoute: typeof AuthenticatedSessionsSessionIdWorkspaceRoute
  AuthenticatedSessionsSessionIdWrapRoute: typeof AuthenticatedSessionsSessionIdWrapRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSessionsNewRoute: AuthenticatedSessionsNewRoute,
  AuthenticatedSessionsSessionIdLobbyRoute:
    AuthenticatedSessionsSessionIdLobbyRoute,
  AuthenticatedSessionsSessionIdWorkspaceRoute:
    AuthenticatedSessionsSessionIdWorkspaceRoute,
  AuthenticatedSessionsSessionIdWrapRoute:
    AuthenticatedSessionsSessionIdWrapRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiElevenlabsScribeTokenRoute: ApiElevenlabsScribeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
